# Generated by Django 4.2.4 on 2023-08-19 06:54

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBlog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('blogTitle', models.CharField(max_length=200)),
                ('projectTitleImage', models.ImageField(upload_to='media/projectBlogImages')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('authorName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('projectCateg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_projectcard', to='Projects.projectcard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
